
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./functiona/
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  TimeFunction2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index2.handler
      Runtime: nodejs6.10
      CodeUri: ./functionb/
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource2
            Method: GET
